name: amar_proshno
description: A simple Flutter Quiz Application - Amar Proshno

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6

flutter:
  uses-material-design: true